main: me.swall.essentialsLite.Main
name: EssentialsLite
version: 0.2
author: swalloich
description: A smaller, newer version of the essentials plugin.

commands:
  fly:
    aliases: [f]
    description: Allows the player to fly regardless of gamemode.
  flySpeed:
    aliases: [fs, fSpeed]
  walkSpeed:
    aliases: [ws, wSpeed]
    description: Changes the speed of the player on the ground
    
permissions:
  essentials.fly:
    description: Allows the player to fly regardless of gamemode
    default: false
  essentials.flySpeed:
    description: Changes the speed the player flys
    default: false
  essentials.walkSpeed:
    description: Changes the speed the player walks
    default: false